id: I6021770B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T20:26:04+00:00'
last_modified: '2022-06-07T17:09:44.292381+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22449
  title: ཚད་མ་རིགས་གཏེར་གྱི་འགྲེལ་པ་ལེགས་བཤད་བཟང་པོ་གསུམ་ལྡན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    AE82:
      image_group_id: I1KG22469
      title: ''
      total_pages: 326
      order: 1
      base_file: AE82.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
